---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches:
      - development
      - master

###############
# Set the Job #
###############
jobs:
  reviewdog:
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: go-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make config/cyml.go

      ################################
      # Run Linter against code base #
      ################################
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          tool_name: golangci-lint # Change reporter name.
          golangci_lint_flags: "--config=.github/.golangci.yml"
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          reporter: github-pr-review
          filter_mode: diff_context
          level: warning # GitHub Status Check won't become failure with this level.
